FROM php:8-fpm
RUN docker-php-ext-install mysqli
# RUN apt-get update && \
#     apt-get install -y locales && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*
# RUN locale-gen es_ES.UTF-8 && dpkg-reconfigure locales
