version: "3.5"
services:
  mysql:
    # image: mysql:5.7
    container_name: mysql
    build: ./database
    ports:
      - "3308:3306"
    env_file: database/.env
    volumes:
      - pena-db:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/dumps:/dumps
    networks:
      - pena-net
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
  php-fpm:
    container_name: php-fpm
    image: php:8-fpm-custom
    build: ./docker/php
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    networks:
      - pena-net
    volumes:
      - ./public:/public
  nginx:
    container_name: nginx
    image: nginx:latest
    links:
      - php-fpm
    depends_on:
      - mysql
      - php-fpm
    networks:
      - pena-net
    ports:
      - "8080:80"
    volumes:
      - ./public:/public
      - ./config/nginx/site.conf:/etc/nginx/conf.d/site.conf
    healthcheck:
      test: service nginx status || exit 1
      interval: 10s
      timeout: 20s
      retries: 10

volumes:
  pena-db:
    external: true

networks:
  pena-net:
    external: true
